### ISSUE TITLE
Rethrow errors caught by riviere

### ISSUE THREAD

**Issue by nikostoulas** [Workable/riviere#13]
As a logging library I would expect riviere to throw again any errors that has caught here:

https://github.com/Workable/riviere/blob/beecd23ee6a5ebb49789d51f4408fe3c334ed61a/index.js#L47

like koa-logger does here:
https://github.com/koajs/logger/blob/master/index.js#L50

**Comment by SokratisVidros** [comment]
That's right. We'll fix that on Monday. Have a nice weekend :)

**Comment by pmatzavin** [comment]
any errors throws withut using riviere will also be thrown when useig riviere. This can be customize using the errors.callback when initalizing the riviere object: https://github.com/Workable/riviere#options_errors_callback

**Comment by pmatzavin** [comment]
the latest release fixes the problem. Now the handling for unexpected errors is done as i have described in my previous comment.
