### ISSUE TITLE
More readable logs

### ISSUE THREAD

**Issue by nikostoulas** [Workable/riviere#24]
![screen shot 2018-05-08 at 16 31 17](https://user-images.githubusercontent.com/1398718/39760138-4890c2a4-52dd-11e8-87bc-a414c22cc44d.png)

![screen shot 2018-05-08 at 16 30 32](https://user-images.githubusercontent.com/1398718/39760113-313192aa-52dd-11e8-89ed-c799e8b3964f.png)

It would make it much more readable for me if the default logs are the second picture.

**Comment by SokratisVidros** [comment]
How about adding some default logging "themes" such as "minimal", "compact", "full", etc...?

**Comment by nikostoulas** [comment]
That would be a nice option
