### ISSUE TITLE
Is this great module available on newer node engine than 6.10.x?

### ISSUE THREAD

**Issue by zj8487** [Workable/riviere#26]
Hi riviere,

I notice the node limitation config in the package.json as follow.
```
  "engines": {
    "node": "6.10.x"
  }
```

is it available on the newer node engine?

**Comment by pmatzavin** [comment]
Hi @zj8487 , It works fine with newer versions:

- Node 8 is officially supported. The Travis CI tests are configured to run the tests with node 8.X.X. ( file `.travis.yml`).

- I expect it works with versions > 8, I will soon add CI tests for versions > 8, and I will remove the  `"node": "6.10.x"` from`package.json` which is outdated and confusing.

Thanks for the feedback!

**Comment by pmatzavin** [comment]
Hi again @zj8487 

I have not found any broking changes in the newer Node versions.
I added node versions `8`, `9`, `10` in  the CI tests.
The updated CI tests pass successfully.
I also updated the `package.json` `engines.node`.

So it is safe to use it with newer Nodejs versions.

Thanks for the feedback! 
Contact me if you have any other problems. 
Bye!
