### ISSUE TITLE
Add documentation about creating a Release

### ISSUE THREAD

**Issue by klouvas** [Workable/riviere#61]
Steps i followed in the past to create a release (on branch of PR):
```
npm version {major|minor|patch}
git tag {version}
git push origin --tags {branch}

# merge PR with merge commit
# copy/paste .npmrc from another project (don't commit the file)

npm publish
```

**Comment by nikostoulas** [comment]
Why do you need .npmrc @klouvas ?

**Comment by nikostoulas** [comment]
This lib is published publicly here https://www.npmjs.com/package/@workablehr/riviere.
To avoid confusion we should probably avoid publishing it to jfrog too.

**Comment by klouvas** [comment]
> Why do you need .npmrc @klouvas ?

I thought it was private. Ignore the part of npmrc.

**Comment by klouvas** [comment]
how do we publish it in npmjs ? do we need to request permission from someone?
cc: @jgerbe

**Comment by nikostoulas** [comment]
@klouvas you have access. I can give access to @jgerbe (@SokratisVidros can also do this). I need his npm username.

**Comment by SokratisVidros** [comment]
I wasn't aware I can deploy :p
